project:
  type: website
  output-dir: docs

website:
  title: "Happy Bday Bby"
  navbar:
    left:
      - href: index.qmd
        text: Freud Poster

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



